### ISSUE TITLE
[yoon_simpimp_2015] Write import script from scratch 

### ISSUE THREAD

**Issue by adriansteffan** [peekbank/peekbank-data-import#121]
Data is on osf
official repo: https://github.com/ejyoon/simpimp
cogsci proceedings paper: https://langcog.stanford.edu/papers/YWF_underreview.pdf

Have not checked yet if all the necessary info is there, might need some further digging before the import is possible

**Comment by vboyce** [comment]
[  ] get stimuli from https://drive.google.com/drive/u/1/folders/1icLwh-9ZGQxmBNEVuYFhFNB6wb4aCQf0

[  ] figure out trial level exclusions if we can find them? the supposedly occurred, but who knows where/when

**Comment by vboyce** [comment]
there are subjects listed as include with either invalid ages or ages out of the reported range

**Comment by vboyce** [comment]
@adriansteffan @mzettersten it seems like the resample in idless import is what's causing the funky graphs

**Comment by mzettersten** [comment]
@vboyce @adriansteffan Ok, obviously a lot more to do w/ this dataset, but I figured out what was going wrong in the processing/ resampling. Commit https://github.com/peekbank/peekbank-data-import/commit/36203bf6bbe879b0d517031c95c4bfdf8fc75852 has the fix

**Comment by mzettersten** [comment]
crux was that there was an issue with how trials were created/ there was a "rezeroing" happening in creating wide.table that was resetting time in a way that is *probably* incorrect --> this in turn caused issues with the base function approx, because (among other things) it appears to expect x values to be ordered (which I can't find documented anywhere). This should always be true within trial for datasets passed to the resampling function

**Comment by mzettersten** [comment]
Some other things to look into:

- [ ] we lose *a lot* of data when joining in the order/ stimulus data. Probably that is non-relevant data (attention getters/ calibration/ etc.), but it would be good to check carefully
- [ ] Can we make sure we are not accidentally including any adult data?
- [ ] It also seems like there are a lot more participants (~250) than participants in the CogSci paper (~150). Does that difference make sense?

**Comment by vboyce** [comment]
from looking at the unfiltered stimuli, it looks like what happened is that the same visual stimuli is played twice in a row (presumably with different audio) 
- first for 8.5 seconds "initial phase":  including 2 seconds of silence and then the phrase "Look at these plates. Elmo’s plate has a carrot."
- then for 1.5 seconds "anticipatory phase": "a chime
sound played to induce participants’ anticipatory gaze"

do we want the anticipatory phase? like we could treat this as 10 seconds of looking data, or we could drop it and have the 8.5?

**Comment by mzettersten** [comment]
I think in principle we could exclude the anticipatory phase, but not sure I'm following - why is there an "anticipatory" phase *after* the presentation of the key stimuli (visual AND auditory)? What is being anticipated? 🤔

**Comment by vboyce** [comment]
I don't understand either. Does @mcfrank remember the rationale? Is it anticipating the appearance of elmo next to his plate?

**Comment by vboyce** [comment]
I ended up keeping the "anticipatory" window as spillover time so that long windows are possible. 

I tracked down and screenshotted the stimuli; it's noted in the Readme, but we're assuming that lines that are identical in the order_list also had the same image and carrier phrase -- looking at it, from what I can tell, this is a reasonable assumption, since the labels we have line up including onset time. 

There are more kids in this data (again in readme), I think it's mostly that there's actually data on a wider range of ages than reported in expt 2, plus a little bit of exclusions not lining up (plus we have the data from the excluded kids)

The overall time course by condition lines up with what's in the paper. (The weirdness in baseline looking by condition is reflected there -- I think this is a preference for looking at the 2-object side over the 1-object side)

Anyhow, I think it's done, but it could definitely use code review to check!

**Comment by mcfrank** [comment]
I believe that the idea was to get anticipation of Elmo's emergence, A) to
make the paradigm more fun for older kids and B) to make sure that kids
knew that the implicatures in the paradigm had a "right answer"...

I think it is reasonable to include the anticipatory window.

I do think it makes sense that there were a wide range of ages since data
were collected at CDM, and our policy was not to turn away any interested
family even if they didn't qualify.

There was definitely a "two object" baseline effect that we observed (in
fact that became part of the theoretical account): implicature is hard
because it pulls for the "one object" solution, which is less salient. In
contrast, mutual-exclusivity type implicatures are easy (and observed
earlier in development) because they typically line up with the more
salient "two object"-type target.

**Comment by mzettersten** [comment]
Ah gotcha, makes sense!!! Like communicating a correct response in this context. Agreed that we can just keep the anticipatory window (unless it complicates import).

Happy to consider the cs trials "vanilla" btw Veronica!

**Comment by vboyce** [comment]
CS trials are now labeled vanilla
