### ISSUE TITLE
Decide what to do about image formats

### ISSUE THREAD

**Issue by benpry** [peekbank/peekbank-data-import#142]
Stimulus images are often in non-standard formats. There are a lot of .pct images and short videos. Should we convert all the images to a standard format as part of importing, like .png? Should we hold onto the originals but also convert to a standard format?

**Comment by adriansteffan** [comment]
I have converted everything into either png or jpg, and we have implemented validation that will throw out warnings for any filetypes that do not adhere to .png, .jpg, and .jpeg

(for now, we wont explicitly fail validation because of this, as the priority on images is still not as high as the priority on import velocity, but all of the existing datasets follow the common formats)
