### ISSUE TITLE
update all templates to schema 2024 once finalized

### ISSUE THREAD

**Issue by mzettersten** [peekbank/peekbank-data-import#72]

**Comment by mzettersten** [comment]
It would also be good to have a CDI data import demo, once we have all the kinks worked out

**Comment by adriansteffan** [comment]
Maybe create future templates using https://github.com/langcog/peekbank-data-import/issues/123, they should be a lot leaner

**Comment by adriansteffan** [comment]
The new command to start both idless and legacy imports provides a commented template and takes care of the overall script structure (tailored to the new v2024 schema). I would argue that any further functionality that targets specific data sources (icoder etc.) should live in central helper functions rather than duplicated templates.  -> Carefully closing this for now.
